### ISSUE TITLE
[BUG] Loss of types

### ISSUE THREAD

**Issue by splincode** [Tinkoff/ng-event-plugins#42] opened 2022-05-26 19:08 UTC
# 🐞 Bug report

### Description

Before

<img width="669" alt="image" src="https://user-images.githubusercontent.com/12021443/170559391-84a20971-ce70-478c-9b4d-74fba66dab0a.png">

After 

<img width="580" alt="image" src="https://user-images.githubusercontent.com/12021443/170559442-d0314218-3480-4f36-bbe8-38172b16b482.png">

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/12021443/170559457-ff0c2fa2-cb60-47f9-8885-25d6b0eed73b.png">

**Comment by waterplea** [comment] 2022-05-27 14:28
Duplicate of https://github.com/Tinkoff/ng-event-plugins/issues/8

**Closed by waterplea** 2022-05-27 14:28 UTC
